// Entirely invented records for the public UI demo. No production inputs are read.
const fs=require('node:fs');
const owners=[{id:'alex',name:'Alex Morgan',email:'alex@example.com'},{id:'sam',name:'Sam Rivera',email:'sam@example.com'}];
const names=['Northstar Labs','Cedar Harbor','Juniper Works','Bluebird Systems'];
const evidence={},companies=[],opportunities=[],priorities=[],drafts=[];
for(let i=0;i<4;i++){
 const id='demo-'+i,name=names[i],owner=owners[i%2].name,ref='demo-evidence-'+i,amount=30000+i*15000;
 const note='Synthetic discovery: the team wants a simpler approval process. Agree on a small pilot and define measurable success criteria.';
 evidence[ref]={ref,nativeId:id,source:'Synthetic CRM',capturedAt:'2026-09-08',title:name+' — pilot discussion',content:note,fields:{owner,stage:'Discovery',amount}};
 const deal={id:'deal-'+id,name:name+' pilot',stage:'discovery',stageLabel:'Discovery/RFP received',amount,currency:'USD',probability:25,close:'2026-12-01',created:'2026-08-01',owner,closed:false,history:[{date:'2026-09-01',label:'Discovery'}],amountHistory:[],closeHistory:[],refs:[ref]};
 const recordingDate=i<2?'2026-08-18T15:00:00Z':'2026-05-02T15:00:00Z';
 const recording={id:'recording-'+id,nativeId:'recording-'+id,title:name+' — Sample discovery',date:recordingDate,minutes:25,recordedBy:owner,invitees:[{name:'Taylor Example',email:'taylor@example.com'}],summary:[{t:'p',x:note}],actions:['Schedule a synthetic pilot review.'],hasTranscript:true,transcriptLines:2,refs:[ref]};
 companies.push({id,name,owner,domain:'example.com',industry:'Software',description:'Fictional company used to demonstrate the workspace.',employees:120,city:'Sample City',country:'Example',lifecycle:'opportunity',created:'2026-08-01',deals:[deal],contacts:[{name:'Taylor Example',email:'taylor@example.com',title:'Operations Lead',refs:[ref]}],notes:[{id:'note-'+id,date:'2026-09-20',text:note,owner,refs:[ref]}],meetings:[{id:'meeting-'+id,title:'Pilot review',start:'2026-08-20T15:00:00Z',outcome:'SCHEDULED'}],tasks:[],calls:[],recordings:[recording],related:[],refs:[ref],completedInteractions:[{date:'2026-09-20',source:'Synthetic discovery',refs:[ref]}],lastContact:'2026-09-20'});
 opportunities.push({id,companyId:'company:'+id,name,dealName:deal.name,owner,stage:deal.stageLabel,amount,probability:.25,close:'2026-12-01',days:7+i,note,refs:[ref]});
 priorities.push({id:'priority-'+id,title:'Agree on the '+name+' pilot',why:'The fictional discovery is complete; scope and success measures are the next decisions.',next:'Review the sample account and prepare a concise follow-up.',caveat:'Synthetic data — no real customer or commitment.',accountIds:['company:'+id],refs:[ref],primary:{label:'Open account',target:{kind:'account',id:'company:'+id}},secondary:{label:'Review draft',target:{kind:'draft',id:'draft-'+id}}});
 drafts.push({id:'draft-'+id,purpose:i===3?'internal-note':'email',title:name+' — next steps',subject:name+' — next steps',text:'Hi Taylor,\n\nHere is a fictional follow-up for the demo. Shall we agree on one pilot workflow and its success criteria?\n\nThanks,\n'+owner,rationale:'Synthetic discovery follow-up.',recipients:'taylor@example.com',cc:'',bcc:'',internalNotes:'Demo only.',campaignSender:'',company:name,accountIds:['company:'+id],supportRefs:[ref],refs:[ref],status:'Draft',version:1,updatedAt:'2026-09-08T12:00:00Z',history:[],contentMode:'default'});
 fs.mkdirSync('out/data/transcripts',{recursive:true});fs.writeFileSync('out/data/transcripts/'+recording.id+'.json',JSON.stringify([{speaker:owner,timestamp:'00:00',text:'This is a synthetic demonstration transcript.'},{speaker:'Taylor Example',timestamp:'00:10',text:'Let us define the pilot and success criteria.'}]));
}
function extraAccount(spec){
 const id=spec.id,ref='demo-evidence-'+id;
 evidence[ref]={ref,nativeId:id,source:'Synthetic CRM',capturedAt:'2026-08-01',title:spec.name+' record',content:'Synthetic record for metric checks.',fields:{owner:spec.owner,stage:spec.stage||'No stage',amount:spec.amount}};
 const deal={id:'deal-'+id,name:spec.dealName||spec.name+' deal',stage:spec.stage||'',stageLabel:spec.stage||'',amount:spec.amount,currency:'USD',probability:spec.probability==null?null:spec.probability,close:spec.close,created:'2026-01-01',owner:spec.owner,closed:false,history:[],amountHistory:[],closeHistory:[],refs:[ref]};
 const company={id,name:spec.name,owner:spec.owner,domain:'example.com',industry:'Software',description:'Fictional company used to demonstrate the workspace.',employees:40,city:'Sample City',country:'Example',lifecycle:'opportunity',created:'2026-01-01',deals:[deal],contacts:[{name:'Taylor Example',email:'taylor@example.com',title:'Operations Lead',refs:[ref]}],notes:[{id:'note-'+id,date:spec.lastContact,text:'Synthetic note.',owner:spec.owner,refs:[ref]}],meetings:[],tasks:[],calls:[],recordings:[],related:[],refs:[ref],completedInteractions:[{date:spec.lastContact,source:'Synthetic note',refs:[ref]}],lastContact:spec.lastContact};
 companies.push(company);
 opportunities.push({id,companyId:'company:'+id,name:spec.name,dealName:deal.name,owner:spec.owner,stage:spec.stage||'',amount:spec.amount,probability:spec.probability==null?null:spec.probability/100,close:spec.close,days:spec.daysInStage,note:'Synthetic.',refs:[ref]});
}
const alex=owners[0].name;
extraAccount({id:'summit',name:'Summit Peak',owner:alex,stage:'Decision',dealName:'Summit Peak expansion',amount:500000,probability:50,close:'2026-12-01',lastContact:'2026-04-20',daysInStage:337});
extraAccount({id:'harbor',name:'Harbor and Co',owner:alex,stage:'Discovery/RFP received',dealName:'Harbor and Co pilot',amount:350000,probability:40,close:'2026-12-01',lastContact:'2026-09-20',daysInStage:12});
extraAccount({id:'nostage',name:'Blank Stage Co',owner:'Owner 8675309',stage:'',dealName:'Blank Stage Co pilot',amount:120000,probability:null,close:'2026-12-15',lastContact:'2026-09-20',daysInStage:null});
extraAccount({id:'past',name:'Past Close Co',owner:alex,stage:'Discovery/RFP received',dealName:'Past Close Co pilot',amount:200000,probability:20,close:'2026-01-15',lastContact:'2026-01-10',daysInStage:400});
extraAccount({id:'renew',name:'Renewal Sample',owner:alex,stage:'Renewal',dealName:'Renewal Sample renewal',amount:80000,probability:80,close:'2026-12-01',lastContact:'2026-09-01',daysInStage:30});
extraAccount({id:'agree',name:'Current Agreement Sample',owner:alex,stage:'Current Agreement',dealName:'Current Agreement Sample agreement',amount:90000,probability:90,close:'2026-12-01',lastContact:'2026-09-01',daysInStage:40});
extraAccount({id:'dq',name:'Disqualified Sample',owner:alex,stage:'Disqualified',dealName:'Disqualified Sample deal',amount:10000,probability:0,close:'2026-12-01',lastContact:'2026-08-01',daysInStage:20});
extraAccount({id:'hold',name:'On Hold Sample',owner:alex,stage:'On Hold',dealName:'On Hold Sample deal',amount:10000,probability:10,close:'2026-12-01',lastContact:'2026-08-01',daysInStage:50});
const leadSources=['Inbound','Outbound','Webinar','Events'];
const quarterLeadDates=['2026-08-17','2026-08-24','2026-08-31','2026-09-07','2026-09-14','2026-09-21'];
const quarterLeadSources=['Inbound','Events','Outbound','Webinar','Inbound','Events'];
const leads=[
 ...Array.from({length:6},(_,i)=>({id:'lead-in-'+i,name:names[i%4],source:quarterLeadSources[i],owner:owners[i%2].name,lead:quarterLeadDates[i],mql:i<2?'2026-08-18':null,sql:i<1?'2026-08-18':null,note:'Fictional sample lead.'})),
 ...Array.from({length:9},(_,i)=>({id:'lead-out-'+i,name:names[i%4],source:leadSources[i%4],owner:owners[i%2].name,lead:'2026-05-'+String(1+i).padStart(2,'0'),mql:null,sql:null,note:'Fictional sample lead outside the quarter.'}))
];
const sheetReview={generatedAt:'2026-09-08T00:00:00Z',sheet:'synthetic',forecast:{buckets:{commit:{stages:['decision','legal'],targets:{'2026-09':200000},label:'Commit'},bestcase:{stages:['wider'],targets:{},label:'Best case'},pipeline:{stages:['discovery','sql','demo'],targets:{},label:'Pipeline'}},month:'2026-09'},mismatches:[],sheetOnly:[],leadTracker:{total:leads.length,unworked:leads.filter(l=>!l.mql).length,recentUnworked:192,mqlNoSql:3}};
const verified={snapshotId:'synthetic-v1',meta:{owners},opportunities,leads,drafts:drafts.map(draft=>({draft})),draftVersions:{},evidenceKeys:{},presentation:{priorities,priorityReview:{id:'synthetic-review',asOf:'2026-09-08',scope:'All records and metrics in this public demo are synthetic.'},suggestedDrafts:[],upcoming:companies.map(c=>({date:'2026-09-15',title:c.name+' pilot review',prep:'Review goals and next steps.',target:{kind:'account',id:'company:'+c.id}}))},quick:{leads:68938,mql:25,sql:3435,note:'Stale lifecycle totals. The workspace recomputes headlines and must not display these.'},report:{meetings:{start:'2026-07-01',end:'2026-09-08',completed:12,recorded:4},pipeline:{weighted:{value:52500},stages:[{stage:'Discovery/RFP received',count:4,amount:210000}],scorecard:[{label:'Active deals',value:4},{label:'Discovery calls',value:12}]},spend:{months:['01','02','03','04','05','06','07','08','09'].map((m,i)=>({month:'2026-'+m,planned:5000+i*500,actual:i===8?null:4500+i*400})),channels:[{name:'Events',amount:8000},{name:'Paid',amount:8000}],channelMonths:[{channel:'Inbound',months:[{month:'2026-07',actual:2000},{month:'2026-08',actual:2000},{month:'2026-09',actual:2000}]},{channel:'Events',months:[{month:'2026-07',actual:4000},{month:'2026-08',actual:4000},{month:'2026-09',actual:null}]}],campaigns:[{name:'Sample introduction',sent:100,replies:12,bounces:2,linkedinSent:25,linkedinReplies:3}],advertising:[]}},web:{start:'2026-07-01',end:'2026-09-08',sessions:1200,engaged:.6,engagedSessions:720,pageViews:2400,aiCited:.25,aiMentioned:.3,aiCount:100,aiEnd:'2026-09-08',visits:Array.from({length:8},(_,i)=>({date:'2026-08-'+String(i*3+1).padStart(2,'0'),value:100+i*20})),channels:[{name:'Organic search',sessions:700,engagedSessions:420,keyEvents:30},{name:'Direct',sessions:500,engagedSessions:300,keyEvents:20}],pages:[{name:'/',sessions:900,engagedSessions:540,keyEvents:35},{name:'/demo',sessions:300,engagedSessions:180,keyEvents:15}]}};
const records={verifiedSnapshotId:'synthetic-v1',generatedAt:'2026-09-08',companies,unmatchedRecordings:[],coverage:{foldedRelated:0,contacts:4,notes:4,fathomTotal:4,transcripts:4}};
const proposals=[{company:'Summit Peak',field:'Close date',currentValue:'Dec 1, 2026',proposedValue:'Dec 15, 2026',rationale:'Synthetic close-date check. Nothing is written back.',by:'assistant',at:'2026-09-26T18:00:00Z',status:'proposed'},{company:'System',field:'verification',currentValue:'',proposedValue:'',rationale:'System verification test only; please decline',by:'assistant',at:'2026-09-26T18:00:00Z',status:'proposed'}];
for(const [name,value]of Object.entries({verified,records,evidence,'crm-proposals':proposals,'draft-seeds':drafts,'evidence-sheet-labels':{},'sheet-review':sheetReview,bootstrap:{user:{id:'demo-user',name:'Demo User',email:'demo@example.com',owner:true},preferences:{mode:'cs',ratings:{},draftModes:{},priorityContext:{}},preferencesRevision:0,drafts,comments:[],connections:{google:{connected:false,configured:false},slack:{connected:false,configured:false}},imported:true,sends:[],campaignSenders:[]}}))fs.writeFileSync('out/data/'+name+'.json',JSON.stringify(value,null,2));
