// Entirely invented records for the public UI demo. No production inputs are read.
const fs=require('node:fs');
const owners=[{id:'alex',name:'Alex Morgan',email:'alex@example.com'},{id:'sam',name:'Sam Rivera',email:'sam@example.com'}];
const names=['Northstar Labs','Cedar Harbor','Juniper Works','Bluebird Systems'];
const evidence={},companies=[],opportunities=[],priorities=[],drafts=[];
for(let i=0;i<4;i++){
 const id='demo-'+i,name=names[i],owner=owners[i%2].name,ref='demo-evidence-'+i,amount=30000+i*15000;
 const note='Synthetic discovery: the team wants a simpler approval process. Agree on a small pilot and define measurable success criteria.';
 evidence[ref]={ref,nativeId:id,source:'Synthetic CRM',capturedAt:'2026-09-08',title:name+' — pilot discussion',content:note,fields:{owner,stage:'Discovery',amount}};
 const deal={id:'deal-'+id,name:name+' pilot',stage:'discovery',stageLabel:'Discovery/RFP received',amount,currency:'USD',probability:25,close:'2026-12-01',created:'2026-08-01',owner,closed:false,history:[{date:'2026-09-01',label:'Discovery'}],amountHistory:[],closeHistory:[],refs:[ref]};
 const recording={id:'recording-'+id,nativeId:'recording-'+id,title:name+' — Sample discovery',date:'2026-09-07T15:00:00Z',minutes:25,recordedBy:owner,invitees:[{name:'Taylor Example',email:'taylor@example.com'}],summary:[{t:'p',x:note}],actions:['Schedule a synthetic pilot review.'],hasTranscript:true,transcriptLines:2,refs:[ref]};
 companies.push({id,name,owner,domain:'example.com',industry:'Software',description:'Fictional company used to demonstrate the workspace.',employees:120,city:'Sample City',country:'Example',lifecycle:'opportunity',created:'2026-08-01',deals:[deal],contacts:[{name:'Taylor Example',email:'taylor@example.com',title:'Operations Lead',refs:[ref]}],notes:[{id:'note-'+id,date:'2026-09-07',text:note,owner,refs:[ref]}],meetings:[{id:'meeting-'+id,title:'Pilot review',start:'2026-09-15T15:00:00Z',outcome:'SCHEDULED'}],tasks:[],calls:[],recordings:[recording],related:[],refs:[ref],completedInteractions:[{date:'2026-09-07',source:'Synthetic discovery',refs:[ref]}],lastContact:'2026-09-07'});
 opportunities.push({id,companyId:'company:'+id,name,owner,stage:deal.stageLabel,amount,probability:.25,close:'2026-12-01',days:7+i,note,refs:[ref]});
 priorities.push({id:'priority-'+id,title:'Agree on the '+name+' pilot',why:'The fictional discovery is complete; scope and success measures are the next decisions.',next:'Review the sample account and prepare a concise follow-up.',caveat:'Synthetic data — no real customer or commitment.',accountIds:['company:'+id],refs:[ref],primary:{label:'Open account',target:{kind:'account',id:'company:'+id}},secondary:{label:'Review draft',target:{kind:'draft',id:'draft-'+id}}});
 drafts.push({id:'draft-'+id,purpose:i===3?'internal-note':'email',title:name+' — next steps',subject:name+' — next steps',text:'Hi Taylor,\n\nHere is a fictional follow-up for the demo. Shall we agree on one pilot workflow and its success criteria?\n\nThanks,\n'+owner,rationale:'Synthetic discovery follow-up.',recipients:'taylor@example.com',cc:'',bcc:'',internalNotes:'Demo only.',campaignSender:'',company:name,accountIds:['company:'+id],supportRefs:[ref],refs:[ref],status:'Draft',version:1,updatedAt:'2026-09-08T12:00:00Z',history:[],contentMode:'default'});
 fs.mkdirSync('out/data/transcripts',{recursive:true});fs.writeFileSync('out/data/transcripts/'+recording.id+'.json',JSON.stringify([{speaker:owner,timestamp:'00:00',text:'This is a synthetic demonstration transcript.'},{speaker:'Taylor Example',timestamp:'00:10',text:'Let us define the pilot and success criteria.'}]));
}
const leads=Array.from({length:24},(_,i)=>({id:'lead-'+i,name:names[i%4],source:['Inbound','Outbound','Webinar'][i%3],owner:owners[i%2].name,lead:'2026-08-'+String(1+i).padStart(2,'0'),mql:i%2?'2026-09-01':null,sql:i%4?'2026-09-05':null,note:'Fictional sample lead.'}));
const verified={snapshotId:'synthetic-v1',meta:{owners},opportunities,leads,drafts:drafts.map(draft=>({draft})),draftVersions:{},evidenceKeys:{},presentation:{priorities,priorityReview:{id:'synthetic-review',asOf:'2026-09-08',scope:'All records and metrics in this public demo are synthetic.'},suggestedDrafts:[],upcoming:companies.map(c=>({date:'2026-09-15',title:c.name+' pilot review',prep:'Review goals and next steps.',target:{kind:'account',id:'company:'+c.id}}))},quick:{leads:24,mql:12,sql:18},report:{meetings:{start:'2026-07-01',end:'2026-09-08',completed:12,recorded:4},pipeline:{weighted:{value:52500},stages:[{stage:'Discovery/RFP received',count:4,amount:210000}],scorecard:[{label:'Active deals',value:4},{label:'Discovery calls',value:12}]},spend:{months:['01','02','03','04','05','06','07','08','09'].map((m,i)=>({month:'2026-'+m,planned:5000+i*500,actual:i===8?null:4500+i*400})),channels:[{name:'Events',amount:12000},{name:'Paid',amount:8000}],campaigns:[{name:'Sample introduction',sent:100,replies:12,bounces:2,linkedinSent:25,linkedinReplies:3}],advertising:[]}},web:{start:'2026-07-01',end:'2026-09-08',sessions:1200,engaged:.6,engagedSessions:720,pageViews:2400,aiCited:.25,aiMentioned:.3,aiCount:100,aiEnd:'2026-09-08',visits:Array.from({length:8},(_,i)=>({date:'2026-08-'+String(i*3+1).padStart(2,'0'),value:100+i*20})),channels:[{name:'Organic search',sessions:700,engagedSessions:420,keyEvents:30},{name:'Direct',sessions:500,engagedSessions:300,keyEvents:20}],pages:[{name:'/',sessions:900,engagedSessions:540,keyEvents:35},{name:'/demo',sessions:300,engagedSessions:180,keyEvents:15}]}};
const records={verifiedSnapshotId:'synthetic-v1',generatedAt:'2026-09-08',companies,unmatchedRecordings:[],coverage:{foldedRelated:0,contacts:4,notes:4,fathomTotal:4,transcripts:4}};
for(const [name,value]of Object.entries({verified,records,evidence,'draft-seeds':drafts,'evidence-sheet-labels':{},bootstrap:{user:{id:'demo-user',name:'Demo User',email:'demo@example.com',owner:true},preferences:{mode:'cs',ratings:{},draftModes:{},priorityContext:{}},preferencesRevision:0,drafts,comments:[],connections:{google:{connected:false,configured:false},slack:{connected:false,configured:false}},imported:true,sends:[],campaignSenders:[]}}))fs.writeFileSync('out/data/'+name+'.json',JSON.stringify(value,null,2));
